version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:12.22
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: Build
          command: npm run build
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
            - node_modules
  test:
    docker:
      - image: cimg/node:12.22
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: Test
          command: npm run test
  analyze:
    docker:
      - image: cimg/node:12.22
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: Analyze
          command: npm run test

workflows:
  orb-free-workflow:
    jobs:
      - test
